/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface App
 */
export interface App {
    /**
     * 
     * @type {number}
     * @memberof App
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof App
     */
    steamId: number;
    /**
     * 
     * @type {string}
     * @memberof App
     */
    name: string;
}

/**
 * Check if a given object implements the App interface.
 */
export function instanceOfApp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "steamId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function AppFromJSON(json: any): App {
    return AppFromJSONTyped(json, false);
}

export function AppFromJSONTyped(json: any, ignoreDiscriminator: boolean): App {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'steamId': json['steam_id'],
        'name': json['name'],
    };
}

export function AppToJSON(value?: App | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'steam_id': value.steamId,
        'name': value.name,
    };
}

