/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewVotingSession
 */
export interface NewVotingSession {
    /**
     * 
     * @type {number}
     * @memberof NewVotingSession
     */
    duration?: number;
    /**
     * 
     * @type {string}
     * @memberof NewVotingSession
     */
    name?: string;
}

/**
 * Check if a given object implements the NewVotingSession interface.
 */
export function instanceOfNewVotingSession(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NewVotingSessionFromJSON(json: any): NewVotingSession {
    return NewVotingSessionFromJSONTyped(json, false);
}

export function NewVotingSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewVotingSession {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function NewVotingSessionToJSON(value?: NewVotingSession | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'duration': value.duration,
        'name': value.name,
    };
}

