/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VotingSession
 */
export interface VotingSession {
    /**
     * 
     * @type {string}
     * @memberof VotingSession
     */
    key: string;
    /**
     * 
     * @type {number}
     * @memberof VotingSession
     */
    endsAt?: number;
    /**
     * 
     * @type {string}
     * @memberof VotingSession
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof VotingSession
     */
    createdAt: string;
    /**
     * 
     * @type {boolean}
     * @memberof VotingSession
     */
    closed: boolean;
}

/**
 * Check if a given object implements the VotingSession interface.
 */
export function instanceOfVotingSession(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "closed" in value;

    return isInstance;
}

export function VotingSessionFromJSON(json: any): VotingSession {
    return VotingSessionFromJSONTyped(json, false);
}

export function VotingSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): VotingSession {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'endsAt': !exists(json, 'ends_at') ? undefined : json['ends_at'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'createdAt': json['created_at'],
        'closed': json['closed'],
    };
}

export function VotingSessionToJSON(value?: VotingSession | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'ends_at': value.endsAt,
        'name': value.name,
        'created_at': value.createdAt,
        'closed': value.closed,
    };
}

