/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VotingItem } from './VotingItem';
import {
    VotingItemFromJSON,
    VotingItemFromJSONTyped,
    VotingItemToJSON,
} from './VotingItem';

/**
 * 
 * @export
 * @interface VotingSessionResult
 */
export interface VotingSessionResult {
    /**
     * 
     * @type {string}
     * @memberof VotingSessionResult
     */
    key: string;
    /**
     * 
     * @type {number}
     * @memberof VotingSessionResult
     */
    endsAt?: number;
    /**
     * 
     * @type {string}
     * @memberof VotingSessionResult
     */
    name?: string;
    /**
     * 
     * @type {Array<VotingItem>}
     * @memberof VotingSessionResult
     */
    items: Array<VotingItem>;
}

/**
 * Check if a given object implements the VotingSessionResult interface.
 */
export function instanceOfVotingSessionResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function VotingSessionResultFromJSON(json: any): VotingSessionResult {
    return VotingSessionResultFromJSONTyped(json, false);
}

export function VotingSessionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): VotingSessionResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'endsAt': !exists(json, 'ends_at') ? undefined : json['ends_at'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'items': ((json['items'] as Array<any>).map(VotingItemFromJSON)),
    };
}

export function VotingSessionResultToJSON(value?: VotingSessionResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'ends_at': value.endsAt,
        'name': value.name,
        'items': ((value.items as Array<any>).map(VotingItemToJSON)),
    };
}

