/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { VotingItem } from './VotingItem';
import {
    VotingItemFromJSON,
    VotingItemFromJSONTyped,
    VotingItemToJSON,
} from './VotingItem';

/**
 * 
 * @export
 * @interface VotingSessionResult
 */
export interface VotingSessionResult {
    /**
     * 
     * @type {string}
     * @memberof VotingSessionResult
     */
    key: string;
    /**
     * 
     * @type {number}
     * @memberof VotingSessionResult
     */
    endsAt?: number;
    /**
     * 
     * @type {string}
     * @memberof VotingSessionResult
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof VotingSessionResult
     */
    createdAt: string;
    /**
     * 
     * @type {boolean}
     * @memberof VotingSessionResult
     */
    closed: boolean;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof VotingSessionResult
     */
    ballot?: { [key: string]: number; };
    /**
     * 
     * @type {boolean}
     * @memberof VotingSessionResult
     */
    hasVoted?: boolean;
    /**
     * 
     * @type {number}
     * @memberof VotingSessionResult
     */
    responses: number;
    /**
     * 
     * @type {Array<VotingItem>}
     * @memberof VotingSessionResult
     */
    items?: Array<VotingItem>;
}

/**
 * Check if a given object implements the VotingSessionResult interface.
 */
export function instanceOfVotingSessionResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "closed" in value;
    isInstance = isInstance && "responses" in value;

    return isInstance;
}

export function VotingSessionResultFromJSON(json: any): VotingSessionResult {
    return VotingSessionResultFromJSONTyped(json, false);
}

export function VotingSessionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): VotingSessionResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'endsAt': !exists(json, 'ends_at') ? undefined : json['ends_at'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'createdAt': json['created_at'],
        'closed': json['closed'],
        'ballot': !exists(json, 'ballot') ? undefined : json['ballot'],
        'hasVoted': !exists(json, 'has_voted') ? undefined : json['has_voted'],
        'responses': json['responses'],
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(VotingItemFromJSON)),
    };
}

export function VotingSessionResultToJSON(value?: VotingSessionResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'ends_at': value.endsAt,
        'name': value.name,
        'created_at': value.createdAt,
        'closed': value.closed,
        'ballot': value.ballot,
        'has_voted': value.hasVoted,
        'responses': value.responses,
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(VotingItemToJSON)),
    };
}

